project:
  type: book
  output-dir: docs

book:
  title: "Statistics Laboratory"
  subtitle: "A Practical Guide for Undergraduate Students"
  author: "Heeyoung Lee"
  date: today
  sidebar:
    logo: logo image.png
  chapters:
    - index.qmd
    - 01_chapter.qmd
    - 02_chapter.qmd

format:
  html:
    theme: cosmo
    css: custom.css
    toc: true
    number-sections: false
    code-copy: true
    html-math-method: mathjax